### ISSUE TITLE
Notification won't go.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct.net-website-bugs#142] opened 2020-04-19 14:55 UTC
## Problem description

When i came onto the forum i had a notification (1 in a circle next to my avatar), it was for a topic i was subscribed to. I unsubscribed but the notification won't go off (theres still the 1 in the circle even though all notifications have been read and visited).

## Steps to reproduce

1.Dont know, as described above.
2.
3.

## Observed result

As described.

## Expected result

The Notification to change to 0.

**Comment by dop2000** [comment] 2020-05-24 04:46
Same happens to me from time to time. It shows that I have 1 notification, even though there are no unread topics, and it sometimes stays like that for a couple of days, then disappears.

**Comment by mOOnpunk** [comment] 2020-05-24 08:13
I wish @TomGullen  would pay as much attention to these bugs as @AshleyScirra does to C3. He can't even be bothered to comment on them, and bugs hardly ever get fixed. He really lets the side down with the website side of things.

**Comment by TomGullen** [comment] 2020-05-24 13:33
@mOOnpunk my role isn't just the website I'm afraid.  This bug is relating to the notification system which needs a complete re-write.  It is on my list but won't be fixed any time soon I'm afraid.

**Comment by dop2000** [comment] 2020-05-24 14:31
Actually, this bug doesn't happen often and doesn't bother me much. There are more annoying issues with the forum which I see almost every day - comments randomly appearing/disappearing, images sometimes not showing, edited comments not updated etc. It feels like some caching or synchronization problem on the server.

**Comment by TheRealDannyyy** [comment] 2020-06-25 17:54
I think this is a duplicate of #81.
Mostly happens when ad-bots post something and it gets deleted before you can check the notifications.

**Closed as completed** 2024-08-13 12:00 UTC
